import type { DashboardViewData } from "@/components/dashboard/DashboardView";

export const demoDashboardData: DashboardViewData = {
  todoData: {
    items: [],
  },

  matchData: {
    players: [
      {
        id: "demo-player-1",
        userId: "demo-user",
        name: "김민수",
        position: "MF",
        detailPositions: ["CM"],
        number: 10,
        appearance: 1,
        goal: 1,
        assist: 0,
      },
      {
        id: "demo-player-2",
        name: "장동혁",
        position: "FW",
        detailPositions: ["ST"],
        number: 9,
        appearance: 1,
        goal: 2,
        assist: 0,
      },
      {
        id: "demo-player-3",
        name: "이재원",
        position: "DF",
        detailPositions: ["CB"],
        number: 4,
        appearance: 1,
        goal: 0,
        assist: 0,
      },
      {
        id: "demo-player-4",
        name: "한승우",
        position: "MF",
        detailPositions: ["CAM"],
        number: 11,
        appearance: 0,
        goal: 0,
        assist: 0,
      },
      {
        id: "demo-player-5",
        name: "정우성",
        position: "GK",
        detailPositions: ["GK"],
        number: 1,
        appearance: 0,
        goal: 0,
        assist: 0,
      },
      {
        id: "demo-player-6",
        name: "윤석현",
        position: "DF",
        detailPositions: ["RB"],
        number: 2,
        appearance: 0,
        goal: 0,
        assist: 0,
      },
    ],

    myPlayer: {
      id: "demo-player-1",
      userId: "demo-user",
      name: "김민수",
      position: "MF",
      detailPositions: ["CM"],
      number: 10,
      appearance: 1,
      appearanceStreak: 1,
      goal: 1,
      assist: 0,
      attackPoint: 1,
      attendanceRate: 100,
    },

    votes: {
      "demo-match-upcoming": [
        { playerId: "demo-player-1", status: "attend" },
        { playerId: "demo-player-2", status: "attend" },
        { playerId: "demo-player-3", status: "pending" },
      ],
      "demo-match-recent": [
        { playerId: "demo-player-1", status: "attend" },
        { playerId: "demo-player-2", status: "attend" },
        { playerId: "demo-player-3", status: "attend" },
      ],
      "demo-match-self": [
        { playerId: "demo-player-1", status: "attend", side: "team_a" },
        { playerId: "demo-player-2", status: "attend", side: "team_b" },
        { playerId: "demo-player-3", status: "attend", side: "team_a" },
        { playerId: "demo-player-4", status: "attend", side: "team_b" },
      ],
    },

    upcomingMatches: [
      {
        id: "demo-match-upcoming",
        seasonId: "demo-season-2026",
        title: "vs FC 유나이티드",
        type: "정규",
        sport: "soccer",
        playersPerSide: 11,
        quarterCount: 4,
        quarterDurationMinutes: 20,
        date: "2026-10-11",
        startTime: "10:00",
        endTime: "12:00",
        voteDeadline: "2026-10-08T18:00",
        location: "서울월드컵보조경기장",
        opponent: "FC 유나이티드",
        uniform: "home",
        status: "scheduled",
        isUpcoming: true,
        countsTowardRecord: true,
      },
    ],

    recentMatch: {
      id: "demo-match-recent",
      seasonId: "demo-season-2026",
      title: "vs 라이벌FC",
      type: "정규",
      sport: "soccer",
      playersPerSide: 11,
      quarterCount: 4,
      quarterDurationMinutes: 20,
      date: "2026-09-21",
      startTime: "10:00",
      endTime: "12:00",
      voteDeadline: "2026-09-18T18:00",
      location: "서울월드컵보조경기장",
      opponent: "라이벌FC",
      uniform: "away",
      status: "scheduled",
      ourScore: 3,
      opponentScore: 1,
      recordCompletedAt: "2026-09-21T13:00:00",
      isUpcoming: false,
      countsTowardRecord: true,
    },

    onChangeMyVote: async () => true,
  },

  statsData: {
    recentResults: ["win"],
    teamSummary: {
      total: 1,
      win: 1,
      draw: 0,
      lose: 0,
      goals: 3,
      conceded: 1,
      winRate: 100,
      goalDiff: 2,
    },
    topAppearance: {
      id: "demo-player-1",
      name: "김민수",
      appearance: 1,
      appearanceStreak: 1,
      goal: 1,
      assist: 0,
      attackPoint: 1,
      attendanceRate: 100,
    },
    topScorer: {
      id: "demo-player-2",
      name: "장동혁",
      appearance: 1,
      appearanceStreak: 1,
      goal: 2,
      assist: 0,
      attackPoint: 2,
      attendanceRate: 100,
    },
    topAssister: {
      id: "demo-player-1",
      name: "김민수",
      appearance: 1,
      appearanceStreak: 1,
      goal: 1,
      assist: 0,
      attackPoint: 1,
      attendanceRate: 100,
    },
  },

  financeData: {
    financeSummary: {
      totalIncome: 165000,
      totalExpense: 70000,
      totalBalance: 95000,
    },
    paymentSummary: {
      paidCount: 4,
      unpaidCount: 2,
      paidRate: 67,
    },
  },

  boardData: {
    recentNotice: [
      {
        id: "demo-post-notice",
        teamId: "demo-team",
        authorId: "demo-user",
        authorName: "김민수",
        type: "notice",
        title: "10월 정기 경기 및 회비 안내",
        content:
          "10월 정기 경기는 매주 토요일 오후 3시에 진행합니다.\n참석 여부를 경기 일정에서 꼭 남겨 주세요.",
        isPinned: true,
        viewCount: 28,
        createdAt: "2026-09-25T10:00:00",
        updatedAt: "2026-09-25T10:00:00",
      },
    ],
  },
};
