import type { MatchItem, MatchRecordMap } from "@/types/match";
import type { TeamSeason } from "@/types/seasons";

export const demoSeasons: TeamSeason[] = [
  {
    id: "demo-season-2026",
    teamId: "demo-team",
    name: "2026 시즌",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    isActive: true,
    createdAt: "2026-01-01T00:00:00",
    updatedAt: "2026-01-01T00:00:00",
  },
];

export const demoMatches: MatchItem[] = [
  {
    id: "demo-match-upcoming",
    seasonId: "demo-season-2026",
    title: "vs FC 유나이티드",
    type: "정규",
    sport: "soccer",
    playersPerSide: 11,
    quarterCount: 4,
    quarterDurationMinutes: 20,
    date: "2026-10-11",
    startTime: "10:00",
    endTime: "12:00",
    voteDeadline: "2026-10-08T18:00",
    opponent: "FC 유나이티드",
    location: "서울월드컵보조경기장",
    uniform: "home",
    status: "scheduled",
    isUpcoming: true,
    countsTowardRecord: true,
  },
  {
    id: "demo-match-recent",
    seasonId: "demo-season-2026",
    title: "vs 라이벌FC",
    type: "정규",
    sport: "soccer",
    playersPerSide: 11,
    quarterCount: 4,
    quarterDurationMinutes: 20,
    date: "2026-09-21",
    startTime: "10:00",
    endTime: "12:00",
    voteDeadline: "2026-09-18T18:00",
    opponent: "라이벌FC",
    location: "서울월드컵보조경기장",
    uniform: "away",
    status: "scheduled",
    ourScore: 3,
    opponentScore: 1,
    recordCompletedAt: "2026-09-21T13:00:00",
    isUpcoming: false,
    countsTowardRecord: true,
  },
  {
    id: "demo-match-self",
    seasonId: "demo-season-2026",
    title: "9월 자체전",
    type: "자체전",
    sport: "futsal",
    playersPerSide: 5,
    quarterCount: 4,
    quarterDurationMinutes: 15,
    date: "2026-09-14",
    startTime: "19:00",
    endTime: "21:00",
    voteDeadline: "2026-09-12T18:00",
    location: "목동 풋살장",
    uniform: "home",
    status: "scheduled",
    ourScore: 5,
    opponentScore: 4,
    recordCompletedAt: "2026-09-14T21:30:00",
    isUpcoming: false,
    countsTowardRecord: false,
  },
];

export const demoMatchRecords: MatchRecordMap = {
  "demo-match-recent": [
    { id: "demo-record-1", type: "goal", playerId: "demo-player-1" },
    { id: "demo-record-2", type: "goal", playerId: "demo-player-2" },
    { id: "demo-record-3", type: "goal", playerId: "demo-player-2" },
    { id: "demo-record-4", type: "concede" },
  ],
  "demo-match-self": [
    { id: "demo-record-5", type: "goal", playerId: "demo-player-1" },
    { id: "demo-record-6", type: "goal", playerId: "demo-player-2" },
    { id: "demo-record-7", type: "goal", playerId: "demo-player-3" },
    { id: "demo-record-8", type: "goal", playerId: "demo-player-4" },
    { id: "demo-record-9", type: "goal", playerId: "demo-player-4" },
    { id: "demo-record-10", type: "concede" },
    { id: "demo-record-11", type: "concede" },
    { id: "demo-record-12", type: "concede" },
    { id: "demo-record-13", type: "concede" },
  ],
};
